<?php

$_SERVER['REQUEST_TIME'];//请求时间
$_SERVER['REQUEST_URI'];//请求URI
$_SERVER['DOCUMENT_ROOT'];//服务器根目录
$_SERVER['REQUEST_METHOD'] ; //请求方法
$_SERVER['HTTP_HOST']; // 域名:端口
$_SERVER['SERVER_PORT']; //服务器端口
$_SERVER['REMOTE_PORT'];//客户端端口
$_SERVER['REMOTE_ADDR'];//客户端IP
$_SERVER['REQUEST_SCHEME']; //协议
$_SERVER['QUERY_STRING'];//查询字符串
$_SERVER['HTTP_X_REQUESTED_WITH'];//xmlhttprequest?